name: My First GitHub Action
on: [push]
jobs:
  project-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: build the project
        run: npm run build
      - name: setup finish
        run: echo "bye"